### ISSUE TITLE
代码疑问

### ISSUE THREAD

**Issue by rich2300** [nubot-nudt/SGLC#1]
作者您好，您的工作十分的充分，但我有一个疑问，你们说你们把你们的工作集成到了ALOAM-框架中，这部分的相关代码我没有看到呢，请问这部分是不开源吗？

**Comment by neng-wang** [comment]
感谢你对我们工作感兴趣！
我们已经把相应的代码放到了这个仓库[SGLC-PGO](https://github.com/neng-wang/SGLC-PGO)。这是一个简易的实现，把SGLC整合到一个位姿图优化框架。代码是比较原始的SGLC版本，由于最近工作繁忙，没有进一步的优化和注释。你可以参考一下。
