### ISSUE TITLE
语义分割时间和聚类时间

### ISSUE THREAD

**Issue by ycx-max** [nubot-nudt/SGLC#3]
作者您好，非常感谢您的工作和分享。我该如何查看语义分割时间和聚类时间？

**Comment by neng-wang** [comment]
感谢你对我们工作感兴趣，语义分割，我们采用的是[SegNet4D](https://github.com/nubot-nudt/SegNet4D)，由于这篇论文还没有被接受，我们暂时还没开源。聚类的时间你可以直接在我们开源的代码中测量[cluster()](https://github.com/nubot-nudt/SGLC/blob/ea000f43eccb61e5b27a4c29b551464292c446e3/semgraph/SemanticGraph.cpp#L248)函数的运行时间。

**Comment by ycx-max** [comment]
感谢您的回答，我已完成聚类时间的测量。请问您方便提供您所用语义分割方法运行的平均时间吗？

**Comment by neng-wang** [comment]
语义分割的平均时间是67.1ms for KITTI，在SegNet4D的论文中也详细报告了这一时间，以及简化后的模型在实际工控机上的运行时间。
