### ISSUE TITLE
位姿估计代码运行问题

### ISSUE THREAD

**Issue by ycx-max** [nubot-nudt/SGLC#4]
[eval_poses:]

![Uploading 2024-11-28 16-33-27 的屏幕截图.png…]()

  cloud_path: "/home/ycx/sglc_ws/kitti/squences/08/velodyne/"
  label_path: "/home/ycx/sglc_ws/SegNet4D_predicitions/kitti/sequences/08/predictions/"
  loop_poses_file: "/home/ycx/sglc_ws/loop_data/loop_poses/distance_based/kitti/08.txt"
  out_file: "/home/ycx/sglc_ws/SGLC/out/kitti/loop_distance4_08.txt"
我按照您的参考，把文件配置路径改成了如上。运行代码时跑到第2961个数据后就停止了，并且frame_count:0
icp average_time:-nan     我应该检查哪里呢？（此时运行结果测试程序时会出现报错ZeroDivisionError: float division by zero，也就是mean_rte = success_rte/success的success部分为0）

**Comment by neng-wang** [comment]
抱歉我不能看到你的截图，可能没有正确的上传。不过，为了方便你check error，我新添加了一个[eval_loop_poses_pair.cpp](https://github.com/nubot-nudt/SGLC/blob/165a8703d6b3ef7e89c0b8cc32e3052dd4fb2471/src/eval_loop_poses_pair.cpp#L1)这可能有帮助的对于你快速找到错误，如果能够正确的运行并且输出位姿，你可以check这个位姿通过[registration_visual.py](https://github.com/nubot-nudt/SGLC/blob/165a8703d6b3ef7e89c0b8cc32e3052dd4fb2471/scripts/registration_visual.py#L1)，并且看到对齐前和对齐后的结果
![Figure_1](https://github.com/user-attachments/assets/2a3a9e7c-e9fb-4baa-8d1d-8000ea4c5e9b)

**Comment by neng-wang** [comment]
额外的提醒一下，loop_distance4_08.txt只有2960个loop pair需要被估计位姿，因此运行程序是正常停止的。至于为什么结果不对，你可以按照我上面的方法测试一下。

**Comment by ycx-max** [comment]
感谢您的回答，我已成功解决。
