### ISSUE TITLE
可视化聚类问题

### ISSUE THREAD

**Issue by rich2300** [nubot-nudt/SGLC#5]
作者您好，请问我已经把show: true remap: true cluster_view: true这几个参数改为true，也把您注释的代码
“// for view  这段代码极其耗费时间，如果不需要可视化，直接关掉”
这部分的代码取消注释了，请问怎么看不到聚类的可视化效果捏？

**Comment by neng-wang** [comment]
您好，
聚类可视化的代码没有在SGLC里面维护，因为可视化是极度时间消耗的，这会加长我们pipeline的运行时间。因此你在SGLC里面尝试打开聚类可视化代码，可能不work。如果你对可视化聚类感兴趣。我已经上传了新的聚类的代码，包括了可视化，你可以在这个[Repositories](https://github.com/neng-wang/CVC_Cluster)里面去尝试。

**Comment by rich2300** [comment]
收到收到，感谢作者的耐心回复~
